set_property SRC_FILE_INFO {cfile:D:/github/Vivado/ArtyS7-Audio/PmodI2S.runs/synth_1/.Xil/Vivado-10820-DESKTOP-08KQHMF/dcp3/clk_wiz_0_in_context.xdc rfile:../dcp3/clk_wiz_0_in_context.xdc id:1 order:EARLY scoped_inst:m_clk} [current_design]
set_property SRC_FILE_INFO {cfile:D:/github/Vivado/ArtyS7-Audio/PmodI2S.srcs/constrs_1/imports/constraints/Arty-S7-50-Rev-E-Master.xdc rfile:../../../../../PmodI2S.srcs/constrs_1/imports/constraints/Arty-S7-50-Rev-E-Master.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells m_clk]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells m_clk]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name m_clk/axis_clk -source [get_ports clk] -edges {1 2 3} -edge_shift {0.000 17.134 34.267} [get_pins m_clk/axis_clk]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
