# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/github/Vivado/ArtyS7-Audio/PmodI2S.cache/wt [current_project]
set_property parent.project_path D:/github/Vivado/ArtyS7-Audio/PmodI2S.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-s7-50:part0:1.1 [current_project]
set_property ip_output_repo d:/github/Vivado/ArtyS7-Audio/PmodI2S.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/github/Vivado/ArtyS7-Audio/PmodI2S.srcs/sources_1/new/axis_dd8_wrapper.v
  D:/github/Vivado/ArtyS7-Audio/PmodI2S.srcs/sources_1/imports/new/axis_i2s2.v
  D:/github/Vivado/ArtyS7-Audio/PmodI2S.srcs/sources_1/imports/DD8_DELAY/dd8_core.v
  D:/github/Vivado/ArtyS7-Audio/PmodI2S.srcs/sources_1/new/top.v
}
read_ip -quiet D:/github/Vivado/ArtyS7-Audio/PmodI2S.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/github/Vivado/ArtyS7-Audio/PmodI2S.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/github/Vivado/ArtyS7-Audio/PmodI2S.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/github/Vivado/ArtyS7-Audio/PmodI2S.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/github/Vivado/ArtyS7-Audio/PmodI2S.srcs/constrs_1/imports/constraints/Arty-S7-50-Rev-E-Master.xdc
set_property used_in_implementation false [get_files D:/github/Vivado/ArtyS7-Audio/PmodI2S.srcs/constrs_1/imports/constraints/Arty-S7-50-Rev-E-Master.xdc]


synth_design -top top -part xc7s50csga324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
